"""
Django settings for Sudarshan_pg project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from pathlib import Path
import os

from dotenv import load_dotenv


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

# Loads variables from:
# D:\Sudarshan_Pg\.env

load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

# IMPORTANT:
# Keep SECRET_KEY in .env when deploying to production.

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-key-change-this"
)

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # --------------------------------------------------------
    # Jazzmin
    # MUST COME BEFORE django.contrib.admin
    # --------------------------------------------------------

    "jazzmin",

    # --------------------------------------------------------
    # Django built-in applications
    # --------------------------------------------------------

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # --------------------------------------------------------
    # Our application
    # --------------------------------------------------------

    "pg",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "Sudarshan_pg.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [

    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # Project-level templates folder
        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI APPLICATION
# ============================================================

WSGI_APPLICATION = "Sudarshan_pg.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

# Currently using SQLite for development.
#
# We can change this to MySQL/PostgreSQL later.

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.sqlite3",

        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# AUTHENTICATION
# ============================================================

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "/user-home/"

LOGOUT_REDIRECT_URL = "/"


# ============================================================
# RAZORPAY
# ============================================================

RAZORPAY_KEY_ID = os.getenv(
    "RAZORPAY_KEY_ID",
    ""
)

RAZORPAY_KEY_SECRET = os.getenv(
    "RAZORPAY_KEY_SECRET",
    ""
)


# ============================================================
# EMAIL
# ============================================================

EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "smtp.gmail.com"
)

EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        "587"
    )
)

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    ""
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    ""
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER
)


# ============================================================
# EMAIL BACKEND
# ============================================================

# If Gmail credentials are available,
# Django will send real emails.
#
# Otherwise, emails will appear in the terminal.

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:

    EMAIL_BACKEND = (
        "django.core.mail.backends.smtp.EmailBackend"
    )

else:

    EMAIL_BACKEND = (
        "django.core.mail.backends.console.EmailBackend"
    )


# ============================================================
# JAZZMIN ADMIN CONFIGURATION
# ============================================================

JAZZMIN_SETTINGS = {

    # --------------------------------------------------------
    # BRANDING
    # --------------------------------------------------------

    "site_title": "Sudarshan PG Admin",

    "site_header": "Sudarshan PG Administration",

    "site_brand": "Sudarshan PG",

    "site_logo": None,

    "login_logo": None,

    "site_icon": None,

    "welcome_sign": "Welcome to Sudarshan PG Management",

    "copyright": "Sudarshan PG",


    # --------------------------------------------------------
    # SIDEBAR
    # --------------------------------------------------------

    "show_sidebar": True,

    "navigation_expanded": True,

    "sidebar_disable_expand": False,


    # --------------------------------------------------------
    # SEARCH
    # --------------------------------------------------------

    "search_model": [

        "auth.User",

        "auth.Group",
    ],


    # --------------------------------------------------------
    # UI OPTIONS
    # --------------------------------------------------------

    "show_ui_builder": False,

    "show_theme_chooser": True,

    "language_chooser": False,

    "use_google_fonts_cdn": True,


    # --------------------------------------------------------
    # FORM SETTINGS
    # --------------------------------------------------------

    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {

        "auth.user": "collapsible",

        "auth.group": "vertical_tabs",
    },


    # --------------------------------------------------------
    # RELATED OBJECT MODALS
    # --------------------------------------------------------

    "related_modal_active": True,


    # --------------------------------------------------------
    # TOP MENU
    # --------------------------------------------------------

    "topmenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": False,
        },

    ],


    # --------------------------------------------------------
    # USER MENU
    # --------------------------------------------------------

    "usermenu_links": [],


    # --------------------------------------------------------
    # ICONS
    # --------------------------------------------------------

    "icons": {

        # Authentication
        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "auth.group": "fas fa-users",

        # Django admin
        "admin.LogEntry": "fas fa-history",

        # PG application
        "pg": "fas fa-building",

        "pg.pgproperty": "fas fa-building",

        "pg.room": "fas fa-bed",

        "pg.tenant": "fas fa-user",

        "pg.booking": "fas fa-calendar-check",

        "pg.payment": "fas fa-credit-card",

        "pg.facility": "fas fa-concierge-bell",

        "pg.review": "fas fa-star",

        "pg.vacaterequest": "fas fa-sign-out-alt",

        "pg.complaint": "fas fa-exclamation-circle",
    },


    # --------------------------------------------------------
    # DEFAULT ICONS
    # --------------------------------------------------------

    "default_icon_parents": "fas fa-folder",

    "default_icon_children": "fas fa-circle",
}


# ============================================================
# JAZZMIN UI TWEAKS
# ============================================================

JAZZMIN_UI_TWEAKS = {

    # --------------------------------------------------------
    # TEXT
    # --------------------------------------------------------

    "navbar_small_text": False,

    "footer_small_text": False,

    "body_small_text": False,

    "brand_small_text": False,


    # --------------------------------------------------------
    # BRAND / ACCENT
    # --------------------------------------------------------

    "brand_colour": "navbar-primary",

    "accent": "accent-primary",


    # --------------------------------------------------------
    # NAVBAR
    # --------------------------------------------------------

    "navbar": "navbar-primary navbar-dark",

    "no_navbar_border": False,

    "navbar_fixed": True,


    # --------------------------------------------------------
    # LAYOUT
    # --------------------------------------------------------

    "layout_boxed": False,

    "footer_fixed": False,


    # --------------------------------------------------------
    # SIDEBAR
    # --------------------------------------------------------

    "sidebar_fixed": True,

    "sidebar": "sidebar-dark-primary",

    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,

    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": False,


    # --------------------------------------------------------
    # THEME
    # --------------------------------------------------------

    "theme": "flatly",

    "dark_mode_theme": "darkly",


    # --------------------------------------------------------
    # BUTTONS
    # --------------------------------------------------------

    "button_classes": {

        "primary": "btn-primary",

        "secondary": "btn-secondary",

        "info": "btn-info",

        "warning": "btn-warning",

        "danger": "btn-danger",

        "success": "btn-success",
    },
}