# Generated by Django 6.1.1 on 2026-09-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏠', help_text='Example: 📶, 🧺, 🚿, 🔒', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing', models.CharField(help_text='Example: 2 Sharing', max_length=50)),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rent in ₹', max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Room Plan',
                'verbose_name_plural': 'Room Plans',
                'ordering': ['display_order', 'rent'],
            },
        ),
    ]
