# Generated by Django 6.1.1 on 2026-09-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='roomplan',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(default='🏠', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='sharing',
            field=models.CharField(max_length=50),
        ),
    ]
