# Generated by Django 6.1.1 on 2026-10-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanagement', '0003_booking_payment_pgproperty_review_room_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='vacancy',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
