# Generated by Django 6.1.1 on 2026-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanagement', '0006_payment_confirmation_email_sent_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
