# Generated by Django 6.1.1 on 2026-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanagement', '0007_alter_tenant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
