# Generated by Django 6.1.1 on 2026-10-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanagement', '0008_alter_tenant_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='pgmanagement.pgproperty'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='pgmanagement.pgproperty'),
        ),
    ]
