# Generated by Django 6.1.1 on 2026-10-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgmanagement', '0009_alter_room_pg_alter_tenant_pg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={},
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pgmanagement.tenant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='sharing_type',
            field=models.CharField(choices=[('2 Sharing', '2 Sharing'), ('3 Sharing', '3 Sharing'), ('4 Sharing', '4 Sharing'), ('5 Sharing', '5 Sharing'), ('Single', 'Single')], default='2 Sharing', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
